Review sprint anne
SW814F20/Report pull request #19
Opened 2020-04-01 15:17 UTC by ACmiester

Der mangler 2 refs til de sektions som Thue og Thomas skriver om, men ellers burde den være done

2020-04-01 15:39 UTC, Tricky12321 requested changes

2020-04-01 15:39 UTC, Tricky12321 commented on report/Sprint_1/Introduction.tex
> +In the following section, will we go into more details about these three goals that we have, and how we completed them.
```suggestion
In the following section, we will go into more details about these three goals that we have, and how we completed them.
```

2020-04-01 15:39 UTC, Tricky12321 commented on report/Sprint_1/Review.tex
> +This section will conclude the first sprint, and highlight how successful this sprint has been.
```suggestion
This section will conclude the first sprint, and highlight how successful the sprint was.
```

2020-04-01 15:39 UTC, Tricky12321 commented on report/Sprint_1/Review.tex
> +Furthermore, in Essence, we need to review our configuration, which can be seen in~\autoref{sec:first-configuration-table}, as we need to use the updated configuration table as input for the next spr
```suggestion
Furthermore, in Essence, we need to review our configuration table, which can be seen in~\autoref{sec:first-configuration-table}, as we need to use the updated configuration table as input for the next sprint.
```

2020-04-01 16:18 UTC, Tricky12321 submitted a review, later dismissed

2020-04-08 16:05 UTC, thomaslhansen commented on report/Sprint_1/Introduction.tex
> +In the following section, we will go into more details about these three goals that we have, and how we completed them.
Der er vist ikke tre goals længere

2020-04-08 16:05 UTC, thomaslhansen commented on report/Sprint_1/Review.tex
> +Furthermore, in Essence, we need to review our configuration table, which can be seen in~\autoref{sec:first-configuration-table}, as we need to use the updated configuration table as input for the ne
Det er vel ikke sikkert at den er opdateret.

2020-04-08 16:06 UTC, thomaslhansen commented on report/Sprint_1/Introduction.tex
> +    \item Create an overview board.
```suggestion
    \item Create an overview board
```
Vel uden . i en itemize

2020-04-08 16:07 UTC, thomaslhansen commented on report/Sprint_1/Review.tex
> +\end{itemize}.
Samme som ovenfor

2020-04-08 16:07 UTC, thomaslhansen commented on report/Sprint_1/Review.tex
> +        \item Yes we have.
```suggestion
        \item Yes we have
```

2020-04-08 16:09 UTC, thomaslhansen commented on report/Sprint_1/Review.tex
> +        \item This one is hard, as we have not any users as of now, but we believe it does have a good user interface
Prøv at omformuler, det giver ingen mening

2020-04-08 16:10 UTC, thomaslhansen commented on report/Sprint_1/Review.tex
> +        \item We have not yet made any translation as of now, we cannot answer this.
```suggestion
        \item We have not yet made any translation as of now, we cannot answer this
```

2020-04-08 16:11 UTC, thomaslhansen commented on report/Sprint_1/Review.tex
> +\end{itemize}
Punktum i itemize

2020-04-08 16:12 UTC, thomaslhansen requested changes
Generalt ser det fint ud, men har sat lidt kommentare

2020-04-08 17:39 UTC, ACmiester commented on report/Sprint_1/Introduction.tex
> +In the following section, we will go into more details about these three goals that we have, and how we completed them.
Har slettet three.

2020-04-08 17:42 UTC, ACmiester commented on report/Sprint_1/Review.tex
> +Furthermore, in Essence, we need to review our configuration table, which can be seen in~\autoref{sec:first-configuration-table}, as we need to use the updated configuration table as input for the ne
Har ændret sætningen

2020-04-08 17:43 UTC, ACmiester commented on report/Sprint_1/Review.tex
> +\end{itemize}
Fixed

2020-04-08 17:43 UTC, ACmiester commented on report/Sprint_1/Review.tex
> +\end{itemize}.
Fixed

2020-04-08 17:45 UTC, ACmiester commented on report/Sprint_1/Review.tex
> +        \item This one is hard, as we have not any users as of now, but we believe it does have a good user interface
Done

2020-04-08 17:58 UTC, thomaslhansen requested changes

2020-04-08 17:58 UTC, thomaslhansen commented on report/Sprint_1/Review.tex
> +                \item App editor where product owner can formalize expected behavior requirements for an interaction model.
Punktum i itemize

2020-04-08 17:58 UTC, thomaslhansen commented on report/Sprint_1/Review.tex
> +            \item Creates a contract between customer and developers.
Punktum i itemize

2020-04-08 17:58 UTC, thomaslhansen commented on report/Sprint_1/Review.tex
> +            \item \textit{Help the customer and developers to get started.}
Punktum i itemize

2020-04-08 18:27 UTC, ACmiester commented on report/Sprint_1/Review.tex
> +            \item \textit{Help the customer and developers to get started.}
Fixed

2020-04-08 18:27 UTC, ACmiester commented on report/Sprint_1/Review.tex
> +            \item Creates a contract between customer and developers.
Fixed

2020-04-08 18:27 UTC, ACmiester commented on report/Sprint_1/Review.tex
> +                \item App editor where product owner can formalize expected behavior requirements for an interaction model.
Fixed

2020-04-08 18:39 UTC, thomaslhansen approved these changes

2020-04-08 18:57 UTC, merged